version: '3'
services:
  bazar-frontend-service:
    build: ./bazar-frontend
    ports:
      - "8080:8080"
    environment:
      - CATALOG_SERVICE_URL=http://bazar-catalog-service:8081
      - ORDER_SERVICE_URL=http://bazar-order-service:8082
    depends_on:
      - bazar-catalog-service
      - bazar-order-service

  bazar-catalog-service:
    build: ./bazar-catalog
    ports:
      - "8081:8081"

  bazar-order-service:
    build: ./bazar-order
    ports:
      - "8082:8082"
    environment:
      - CATALOG_SERVICE_URL=http://bazar-catalog-service:8081
    depends_on:
      - bazar-catalog-service
